# Generated by Django 2.2.1 on 2019-12-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        ('users', '0001_initial'),
        ('fec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='follower_list',
            field=models.ManyToManyField(blank=True, to='users.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='expert',
            name='industry',
            field=models.ManyToManyField(blank=True, to='expert.Industries', verbose_name='Industries'),
        ),
        migrations.AddField(
            model_name='expert',
            name='language',
            field=models.ManyToManyField(to='fec_app.Languages'),
        ),
    ]
