# Generated by Django 2.2.1 on 2019-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20191225_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('100', 'Agencies'), ('200', 'Employees')], default='100', max_length=255, verbose_name='Expert Type')),
            ],
            options={
                'verbose_name': 'Expert Type',
                'verbose_name_plural': 'Expert Types',
            },
        ),
        migrations.AlterField(
            model_name='availability',
            name='type',
            field=models.CharField(choices=[('100', 'New opportunities'), ('200', 'Freelancer'), ('300', 'Full Time')], default='100', max_length=255, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='expert',
            name='type',
            field=models.ManyToManyField(to='expert.ExpertTypes'),
        ),
    ]
