# Generated by Django 2.2.1 on 2019-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20191227_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='availability',
            field=models.ManyToManyField(blank=True, to='expert.Availability'),
        ),
    ]
