# Generated by Django 2.2.1 on 2020-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_auto_20191227_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='language',
            field=models.ManyToManyField(blank=True, to='fec_app.Languages'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='type',
            field=models.ManyToManyField(blank=True, to='expert.ExpertTypes'),
        ),
    ]
