# Generated by Django 2.2.1 on 2020-02-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_expert_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experttags1',
            options={'verbose_name': 'Field of Expertise', 'verbose_name_plural': 'Fields of Expertise'},
        ),
        migrations.AlterField(
            model_name='experttags1',
            name='expertise_fields',
            field=models.CharField(max_length=255, verbose_name='Fields of Expertise:'),
        ),
        migrations.CreateModel(
            name='ExpertColleagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleague', to='expert.Expert')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Expert')),
            ],
            options={
                'verbose_name': 'Expert Colleague',
                'verbose_name_plural': 'Expert Colleagues',
            },
        ),
    ]
