# Generated by Django 2.2.1 on 2020-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_expertprofilecompilation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertprofilecompilation',
            options={'verbose_name': 'Expert Profile Compilation', 'verbose_name_plural': 'Expert Profile Compilation'},
        ),
        migrations.AlterField(
            model_name='expertprofilecompilation',
            name='icon_url',
            field=models.CharField(max_length=120),
        ),
    ]
