# Generated by Django 2.2.1 on 2020-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_auto_20200304_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='complation_percentage',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='expertprofilecompilation',
            name='icon_url',
            field=models.CharField(default='not_completed', max_length=120),
        ),
    ]
