# Generated by Django 2.2.1 on 2020-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_auto_20200304_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expertprofilecompilation',
            name='icon_url',
            field=models.CharField(default='not_completed.png', max_length=120),
        ),
    ]
