# Generated by Django 2.2.1 on 2020-03-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0013_auto_20200304_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='completion_percentage',
            field=models.IntegerField(default='0'),
        ),
    ]
