# Generated by Django 2.2.1 on 2020-03-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fec_app', '0004_languagelevel'),
        ('expert', '0014_auto_20200305_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Expert')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fec_app.Languages')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fec_app.LanguageLevel')),
            ],
        ),
    ]
