# Generated by Django 2.2.1 on 2020-03-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_expertlanguages'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='et_points',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expert',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
