# Generated by Django 2.2.1 on 2020-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_auto_20200307_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='et_points',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
