# Generated by Django 2.2.1 on 2020-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0018_auto_20200331_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='type',
            field=models.CharField(choices=[('New opportunities', 'New opportunities'), ('Freelancer', 'Freelancer'), ('Full Time', 'Full Time')], default='Full Time', max_length=255, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='experttypes',
            name='type',
            field=models.CharField(choices=[('Agencies', 'Agencies'), ('Employees', 'Employees')], default='Employees', max_length=255, verbose_name='Expert Type'),
        ),
    ]
