# Generated by Django 2.2.1 on 2019-12-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        ('companies', '0002_auto_20191225_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='follower_list',
            field=models.ManyToManyField(blank=True, related_name='followed_events', to='users.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='events.EventSponsors'),
        ),
        migrations.AddField(
            model_name='aggrevents',
            name='company',
            field=models.ManyToManyField(to='companies.Company'),
        ),
    ]
