# Generated by Django 2.2.1 on 2020-01-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggrevents',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
