# Generated by Django 2.2.1 on 2020-01-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20200122_1412'),
        ('events', '0004_auto_20200118_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer'),
        ),
    ]
