# Generated by Django 2.2.1 on 2020-02-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='events.Tags'),
        ),
    ]
