# Generated by Django 2.2.1 on 2020-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200209_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(null=True),
        ),
    ]
