# Generated by Django 2.2.1 on 2020-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_ticket_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket_link',
            new_name='refund_policy_url',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(null=True),
        ),
    ]
