# Generated by Django 2.2.1 on 2020-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200220_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='events.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='percentage',
            field=models.IntegerField(default=0, null=True, verbose_name='Refund Percentage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsor',
            field=models.ManyToManyField(blank=True, null=True, to='events.EventSponsors'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_event_dt',
            field=models.DateTimeField(null=True, verbose_name='Start Time'),
        ),
    ]
