# Generated by Django 2.2.1 on 2020-02-22 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200222_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='refund_days',
            field=models.IntegerField(default=0, null=True, verbose_name='How many days before Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='events.EventSponsors'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_event_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
