# Generated by Django 2.2.1 on 2020-02-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200222_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='refund',
            new_name='no_refund',
        ),
    ]
