# Generated by Django 2.2.1 on 2020-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_auto_20200122_1810'),
        ('events', '0013_auto_20200222_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(to='organizer.Organizer'),
        ),
    ]
