# Generated by Django 2.2.1 on 2020-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200222_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_type',
            field=models.CharField(choices=[('100', 'By Email'), ('200', 'On our website Form')], default='100', max_length=255, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_web_site',
            field=models.URLField(null=True),
        ),
    ]
