# Generated by Django 2.2.1 on 2020-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200222_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='application_type',
            field=models.BooleanField(default=False),
        ),
    ]
