# Generated by Django 2.2.1 on 2020-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200222_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(related_name='events', to='organizer.Organizer'),
        ),
    ]
