# Generated by Django 2.2.1 on 2020-04-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200401_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_website',
            field=models.URLField(null=True),
        ),
    ]
