# Generated by Django 2.2.1 on 2020-04-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_source_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='source_website',
            new_name='source_url',
        ),
    ]
