# Generated by Django 2.2.1 on 2020-04-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='source_url',
            new_name='source_website',
        ),
    ]
