# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
	("aa", _(u"Afar")),
	("ab", _(u"Abkhazian")),
    ("aa", _(u"Afar")),
    ("af", _(u"Afrikaans")),
    ("ak", _(u"Akan")),
    ("sq", _(u"Albanian")),
    ("am", _(u"Amharic")),
    ("ar", _(u"Arabic")),
    ("an", _(u"Aragonese")),
    ("hy", _(u"Armenian")),
    ("as", _(u"Assamese")),
    ("av", _(u"Avaric")),
    ("ae", _(u"Avestan")),
    ("ay", _(u"Aymara")),
    ("az", _(u"Azerbaijani")),
    ("bm", _(u"Bambara")),
    ("ba", _(u"Bashkir")),
    ("eu", _(u"Basque")),
    ("be", _(u"Belarusian")),
    ("bn", _(u"Bengali (Bangla)")),
    ("bh", _(u"Bihari")),
    ("bi", _(u"Bislama")),
    ("bs", _(u"Bosnian")),
    ("br", _(u"Breton")),
    ("bg", _(u"Bulgarian")),
    ("my", _(u"Burmese")),
    ("ca", _(u"Catalan")),
    ("ch", _(u"Chamorro")),
    ("ce", _(u"Chechen")),
    ("zh", _(u"Chinese")),
    ("zh-Hans", _(u"Chinese (Simplified)")),
    ("zh-Hant", _(u"Chinese (Traditional)")),
    ("cv", _(u"Chuvash")),
    ("kw", _(u"Cornish")),
    ("co", _(u"Corsican")),
    ("cr", _(u"Cree")),
    ("hr", _(u"Croatian")),
    ("cs", _(u"Czech")),
    ("da", _(u"Danish")),
    ("nl", _(u"Dutch")),
    ("dz", _(u"Dzongkha")),
    ("en", _(u"English")),
    ("eo", _(u"Esperanto")),
    ("et", _(u"Estonian")),
    ("ee", _(u"Ewe")),
    ("fo", _(u"Faroese")),
    ("fj", _(u"Fijian")),
    ("fi", _(u"Finnish")),
    ("fr", _(u"French")),
    ("gl", _(u"Galician")),
    ("gd", _(u"Gaelic (Scottish)")),
    ("gv", _(u"Gaelic (Manx)")),
    ("ka", _(u"Georgian")),
    ("de", _(u"German")),
    ("el", _(u"Greek")),
    ("kl", _(u"Greenlandic")),
    ("gn", _(u"Guarani")),
    ("gu", _(u"Gujarati")),
    ("ht", _(u"Haitian Creole")),
    ("ha", _(u"Hausa")),
    ("he", _(u"Hebrew")),
    ("hz", _(u"Herero")),
    ("hi", _(u"Hindi")),
    ("ho", _(u"Hiri Motu")),
    ("hu", _(u"Hungarian")),
    ("is", _(u"Icelandic")),
    ("io", _(u"Ido")),
    ("ig", _(u"Igbo")),
    ("in", _(u"Indonesian")),
    ("ia", _(u"Interlingua")),
    ("ie", _(u"Interlingue")),
    ("iu", _(u"Inuktitut")),
    ("ik", _(u"Inupiak")),
    ("ga", _(u"Irish")),
    ("it", _(u"Italian")),
    ("ja", _(u"Japanese")),
    ("jv", _(u"Javanese")),
    ("kl", _(u"Kalaallisut, Greenlandic")),
    ("kn", _(u"Kannada")),
    ("kr", _(u"Kanuri")),
    ("ks", _(u"Kashmiri")),
    ("kk", _(u"Kazakh")),
    ("km", _(u"Khmer")),
    ("ki", _(u"Kikuyu")),
    ("rw", _(u"Kinyarwanda (Rwanda)")),
    ("rn", _(u"Kirundi")),
    ("ky", _(u"Kyrgyz")),
    ("kv", _(u"Komi")),
    ("kg", _(u"Kongo")),
    ("ko", _(u"Korean")),
    ("ku", _(u"Kurdish")),
    ("kj", _(u"Kwanyama")),
    ("lo", _(u"Lao")),
    ("la", _(u"Latin")),
    ("lv", _(u"Latvian (Lettish)")),
    ("li", _(u"Limburgish ( Limburger)")),
    ("ln", _(u"Lingala")),
    ("lt", _(u"Lithuanian")),
    ("lu", _(u"Luga-Katanga")),
    ("lg", _(u"Luganda, Ganda")),
    ("lb", _(u"Luxembourgish")),
    ("gv", _(u"Manx")),
    ("mk", _(u"Macedonian")),
    ("mg", _(u"Malagasy")),
    ("ms", _(u"Malay")),
    ("ml", _(u"Malayalam")),
    ("mt", _(u"Maltese")),
    ("mi", _(u"Maori")),
    ("mr", _(u"Marathi")),
    ("mh", _(u"Marshallese")),
    ("mo", _(u"Moldavian")),
    ("mn", _(u"Mongolian")),
    ("na", _(u"Nauru")),
    ("nv", _(u"Navajo")),
    ("ng", _(u"Ndonga")),
    ("nd", _(u"Northern Ndebele")),
    ("ne", _(u"Nepali")),
    ("no", _(u"Norwegian")),
    ("nb", _(u"Norwegian bokmål")),
    ("nn", _(u"Norwegian nynorsk")),
    ("ii", _(u"Nuosu")),
    ("oc", _(u"Occitan")),
    ("oj", _(u"Ojibwe")),
    ("or", _(u"Oriya")),
    ("om", _(u"Oromo (Afaan Oromo)")),
    ("os", _(u"Ossetian")),
    ("pi", _(u"Pāli")),
    ("ps", _(u"Pashto, Pushto")),
    ("fa", _(u"Persian (Farsi)")),
    ("pl", _(u"Polish")),
    ("pt", _(u"Portuguese")),
    ("pa", _(u"Punjabi (Eastern)")),
    ("qu", _(u"Quechua")),
    ("rm", _(u"Romansh")),
    ("ro", _(u"Romanian")),
    ("ru", _(u"Russian")),
    ("se", _(u"Sami")),
    ("sm", _(u"Samoan")),
    ("sg", _(u"Sango")),
    ("sa", _(u"Sanskrit")),
    ("sr", _(u"Serbian")),
    ("sh", _(u"Serbo-Croatian")),
    ("st", _(u"Sesotho")),
    ("tn", _(u"Setswana")),
    ("sn", _(u"Shona")),
    ("ii", _(u"Sichuan Yi")),
    ("sd", _(u"Sindhi")),
    ("si", _(u"Sinhalese")),
    ("ss", _(u"Siswati")),
    ("sk", _(u"Slovak")),
    ("sl", _(u"Slovenian")),
    ("so", _(u"Somali")),
    ("nr", _(u"Southern Ndebele")),
    ("es", _(u"Spanish")),
    ("su", _(u"Sundanese")),
    ("sw", _(u"Swahili (Kiswahili)")),
    ("ss", _(u"Swati")),
    ("sv", _(u"Swedish")),
    ("tl", _(u"Tagalog")),
    ("ty", _(u"Tahitian")),
    ("tg", _(u"Tajik")),
    ("ta", _(u"Tamil")),
    ("tt", _(u"Tatar")),
    ("te", _(u"Telugu")),
    ("th", _(u"Thai")),
    ("bo", _(u"Tibetan")),
    ("ti", _(u"Tigrinya")),
    ("to", _(u"Tonga")),
    ("ts", _(u"Tsonga")),
    ("tr", _(u"Turkish")),
    ("tk", _(u"Turkmen")),
    ("tw", _(u"Twi")),
    ("ug", _(u"Uyghur")),
    ("uk", _(u"Ukrainian")),
    ("ur", _(u"Urdu")),
    ("uz", _(u"Uzbek")),
    ("ve", _(u"Venda")),
    ("vi", _(u"Vietnamese")),
    ("vo", _(u"Volapük")),
    ("wa", _(u"Wallon")),
    ("cy", _(u"Welsh")),
    ("wo", _(u"Wolof")),
    ("fy", _(u"Western Frisian")),
    ("xh", _(u"Xhosa")),
    ("yo", _(u"Yoruba")),
    ("za", _(u"Zhuang, Chuang")),
    ("zu", _(u"Zulu")),
)