# Generated by Django 2.2.1 on 2019-12-25 00:03

import custom.custom_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('article_img', models.ImageField(blank=True, null=True, upload_to=custom.custom_tools.get_news_img_path, verbose_name='News Photo')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('sponsored', models.BooleanField(default=False)),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='news.Tags')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
