# Generated by Django 2.2.1 on 2019-12-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('excellent', models.FloatField(default=0, max_length=20)),
                ('great', models.FloatField(default=0, max_length=20)),
                ('average', models.FloatField(default=0, max_length=20)),
                ('poor', models.FloatField(default=0, max_length=20)),
                ('bad', models.FloatField(default=0, max_length=20)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='ReportCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Report Category Title')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name=' Report Category Description')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content', models.TextField(blank=True, max_length=1024, verbose_name='Content')),
                ('content_title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Content Title')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('score', models.FloatField(default=0, null=True, verbose_name='Score')),
                ('anon', models.BooleanField(default=False)),
                ('reviewer_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reviewer Name')),
                ('position', models.CharField(blank=True, max_length=40, null=True)),
                ('tags', models.CharField(blank=True, max_length=40, null=True)),
                ('rating_flag', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Report Title')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews_and_rating.ReportCategories')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews_and_rating.ReviewModel')),
            ],
        ),
    ]
