# Generated by Django 2.2.1 on 2020-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec_app', '0002_emaillist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillist',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AddField(
            model_name='emaillist',
            name='email_updates',
            field=models.BooleanField(default=False),
        ),
    ]
