# Generated by Django 2.2.1 on 2020-03-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fec_app', '0005_importcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportCompany',
        ),
    ]
