# Generated by Django 2.2.1 on 2020-01-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerEventsPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
            options={
                'verbose_name': 'Past Events Photo',
                'verbose_name_plural': 'Past Events Photos',
            },
        ),
    ]
