# Generated by Django 2.2.1 on 2020-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200118_1611'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
