# Generated by Django 2.2.1 on 2020-01-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0002_organizer_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='events',
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
