# Generated by Django 2.2.1 on 2020-01-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20200122_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
            options={
                'verbose_name': 'Organizer Subscriber',
                'verbose_name_plural': 'Organizer Subcribers',
            },
        ),
    ]
