# Generated by Django 2.2.1 on 2020-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_organizersubscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizersubscribers',
            options={'verbose_name': 'Organizer Subscriber', 'verbose_name_plural': 'Organizer Subscribers'},
        ),
    ]
