# Generated by Django 2.2.1 on 2019-12-25 00:03

import ckeditor_uploader.fields
import custom.custom_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Company Info')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=custom.custom_tools.get_company_logo_path, verbose_name='Company Logo')),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('avg_rating', models.FloatField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Type Name:')),
            ],
            options={
                'verbose_name': 'Company Type',
                'verbose_name_plural': 'Company Types',
            },
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='Market Name:')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name:')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Product Info')),
                ('img', models.ImageField(blank=True, null=True, upload_to=custom.custom_tools.get_companyproduct_img_path, verbose_name='Product Image')),
                ('avg_rating', models.FloatField(blank=True, default=0, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ManyToManyField(to='companies.Company')),
            ],
            options={
                'verbose_name': 'Company Product',
                'verbose_name_plural': 'Company Products',
            },
        ),
    ]
