# Generated by Django 2.2.1 on 2019-12-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='follower_list',
            field=models.ManyToManyField(blank=True, to='users.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='company',
            name='markets',
            field=models.ManyToManyField(blank=True, to='companies.Markets'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(blank=True, to='companies.CompanyTypes'),
        ),
    ]
