# Generated by Django 2.2.1 on 2020-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191225_0403'),
    ]

    operations = [

    ]
