# Generated by Django 2.2.1 on 2020-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191225_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='startup',
            field=models.BooleanField(default=False),
        ),
    ]
