# Generated by Django 2.2.1 on 2020-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_startup'),
    ]