# Generated by Django 2.2.1 on 2020-04-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200310_2039'),
        ('companies', '0003_company_startup'),
    ]

    operations = [
    ]
