# Generated by Django 2.2.1 on 2020-04-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200401_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
