# Generated by Django 2.2.1 on 2020-04-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_20200401_1910'),
        ('companies', '0006_company_user'),
    ]

    operations = [
    ]
