# Generated by Django 2.2.1 on 2020-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20200410_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='single_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
