# Generated by Django 2.2.1 on 2020-04-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20200410_1323'),
        ('companies', '0007_merge_20200408_2117'),
    ]

    operations = [
    ]
