# Generated by Django 2.2.1 on 2020-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_zibil_duzelden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avg_rating',
            field=models.FloatField(blank=True, default=80, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
